--- #YAML:1.0
name:               FlatFile-DataStore
version:            1.01
abstract:           Perl module that implements a flatfile
author:
    - Brad Baxter <bbaxter@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Omap:      0.06
    Math::Int2Base:  0.03
    URI:             1.35
    URI::Escape:     1.35
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
